site_name: DevOps-Documentation
site_author: Rajiv Gopal Singh
site_url: https://blog.rajivgopalsingh.com.np
 
nav:
  - Home: 
    - index.md
    - Scripting: Scripting/bash.md
    - Monitoring: Monitoring/1. setup_prometheus-grafana.md 
    - Logging: Logging/kafka.md
    - Security:  Security/KubeScape.md
    - Kubernetes: Kubernetes/Introduction/intro.md
  - Monitoring: 
    - Monitoring/1. setup_prometheus-grafana.md
    - Monitoring/2. gmail_integration.md
    - Monitoring/3. slack_integration.md
  - Logging: Logging/kafka.md
  - Security:  
    - Security/KubeScape.md
    - Security/M9Sweeper.md  
  - Troubleshoots:
    - Troubleshoots/How to rotate and renew expired Contou.md
  - Traefik:
    - Traefik/Traefik.md

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png
  language: en

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RajivGS
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajivgs/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@whitelotus8063

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true